Merge PR #311, #312, #314, #315 and #320 into main (#321)
* Add smart-contract search entry point (#287)

* Add playgrounds (#288)

* Bump axios from 0.21.1 to 0.21.4 (#285)

Bumps [axios](https://github.com/axios/axios) from 0.21.1 to 0.21.4.
- [Release notes](https://github.com/axios/axios/releases)
- [Changelog](https://github.com/axios/axios/blob/master/CHANGELOG.md)
- [Commits](https://github.com/axios/axios/compare/v0.21.1...v0.21.4)

---
updated-dependencies:
- dependency-name: axios
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Fixes Cardano Explorer and Pull Request Template links (#272)

* changes the default language of a link's site to English

* fixes link to pull request template in contributing document

Co-authored-by: Tommy

* Adding alonzo genesis files (#291)

* Adding alonzo genesis files

* Update running-cardano.md

* fix typo (#305)

* fix typo

* september spotlight interview

Co-authored-by: Kevin Cislak 

* Removing the random constraint for building wallet (#297)

Building the wallet with `--constraint="random<1.2"` results in:

```
Building library for cardano-wallet-core-2021.9.9..
[59 of 95] Compiling Cardano.Wallet.DB.Sqlite.Types ( src/Cardano/Wallet/DB/Sqlite/Types.hs, /home/cardano/cardano-src/cardano-wallet/dist-newstyle/build/x86_64-linux/ghc-8.10.7/cardano-wallet-core-2021.9.9/build/Cardano/Wallet/DB/Sqlite/Types.o, /home/cardano/cardano-src/cardano-wallet/dist-newstyle/build/x86_64-linux/ghc-8.10.7/cardano-wallet-core-2021.9.9/build/Cardano/Wallet/DB/Sqlite/Types.dyn_o )

src/Cardano/Wallet/DB/Sqlite/Types.hs:122:1: error:
    Could not load module ‘System.Random.Internal’
    It is a member of the hidden package ‘random-1.2.0’.
    Perhaps you need to add ‘random’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
    |
122 | import System.Random.Internal
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build cardano-wallet-core-2021.9.9 (which is required by
exe:local-cluster from cardano-wallet-2021.9.9, test:integration from
cardano-wallet-2021.9.9 and others).
```

Issue here: https://github.com/input-output-hk/cardano-wallet/issues/2824
Raising this PR to discuss as I don't understand the significance of removing the constraint.

Versions:
* cardano-wallet tag v2021-09-09
* cabal-install version 3.4.0.0
* compiled using version 3.4.0.0 of the Cabal library
* The Glorious Glasgow Haskell Compilation System, version 8.10.7
* Ubuntu 20.04.3 LTS

* september spotlight article (#306)

Co-authored-by: Kevin Cislak

* Update creating-wallet-faucet.md (#307)

* Update creating-wallet-faucet.md

* Update creating-wallet-faucet.md

* Delete duplicate article (#310)

* Use `HydraBuildList` to provide latest release binaries (with fallback) (#300)

* Bump prismjs from 1.24.1 to 1.25.0 (#311)

Bumps [prismjs](https://github.com/PrismJS/prism) from 1.24.1 to 1.25.0.
- [Release notes](https://github.com/PrismJS/prism/releases)
- [Changelog](https://github.com/PrismJS/prism/blob/master/CHANGELOG.md)
- [Commits](https://github.com/PrismJS/prism/compare/v1.24.1...v1.25.0)

---
updated-dependencies:
- dependency-name: prismjs
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix broken faucet link (#312)

* fix broken faucet link

* Update testnets-and-devnets.md

* Update testnets-and-devnets.md

adding relative paths to the docs/integrate-cardano/testnet-faucet/ url

* Update testnets-and-devnets.md

replaced the problematic url with /docs/whatever as an interim solution just to get the link to work for now

* minor bug (#314)

added the 0x prefix, which is needed for the CLI to recognize the string as a byte array

* Spotlight fixes (#315)

* Fix spotlight article date

* Fix inconsistent tag

* Varia (#320)

* Fix Gimbalab changes

* Add two videos to technical concepts page

* Add PC fund 5 voting results

* Refresh discord invitation link

* Remove outdated note box

* Improve integrate Cardano overview

* Fix inconsistent tAda (test ada) spellings

* Start editorial style guide

* Fix inconsistent ada spellings

* Update Editorial Style Guide

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Rodrigo Matos
Co-authored-by: John Imison 
Co-authored-by: cislakk 
Co-authored-by: Kevin Cislak
Co-authored-by: Javier La Banca 
Co-authored-by: Alexander Klee 
Co-authored-by: AVA 
Co-authored-by: Martin Lang